<?php

define('CFG_FILES_DIR', CFG_ROOT.'/files');
define('CFG_DATA_DIR',  CFG_ROOT.'/sys/data');
define('CFG_LIB_DIR',   CFG_ROOT.'/sys/inc/lib');
define('CFG_CLS_DIR',   CFG_ROOT.'/sys/inc/cls');
define('CFG_INC_DIR',   CFG_ROOT.'/sys/inc/inc');
define('CFG_UPL_DIR',   CFG_ROOT.'/files/upload');
define('CFG_TPL_DIR',   CFG_ROOT.'/sys/tpl');

define('CFG_DB_HOST',      'mysql_host');
define('CFG_DB_USER',      'mysql_user');
define('CFG_DB_PASS',      'mysql_pass');
define('CFG_DB_NAME',      'mysql_dbname');
define('CFG_DB_PREF',      '');
define('CFG_ADMIN_NAME',   'admin');
define('CFG_ADMIN_PASS',   '123');
//define('CFG_SITE',         'afisha-kino.su/abc/task');
define('CFG_SITE',         'localhost/beejee');